name: Packer Validation

env:
  CI: true
  ssh_username: "ubuntu"
  GITHUB_REPO_PATH: ${{ github.workspace }}



on:
  push:
    branches: [main]
  
jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      #Compressing the repository
      - name: Zip the repository
        run: zip -r webapp.zip . -x ".git/*" ".github/*"


      # - name: Build Packer Template
      #   uses: ExitoLab/packer_build_action_aws@v0.2.10
      #   with:
      #     templateFile: "base_ami.json"
      #     workingDir: "packer"

      # Initialize Packer templates
      - name: Initialize Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ${{ github.workspace }}/packer/base_ami.json.pkr.hcl


      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ${{ github.workspace }}/packer/base_ami.json.pkr.hcl

      # build AMI
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ${{ github.workspace }}/packer/base_ami.json.pkr.hcl
        env:
          PACKER_LOG: 1

# =================


